filename: app
spring:

  datasource:
    url: jdbc:postgresql://localhost:5432/local
    username: local
    password: local

socnet:
  vk:
    appId: 123456789
    secretKey: "vk_secret_key"
# @todo-a vk secretKey and teelgram token???
alerter:
  telegram:
    chatId: -1234567890123
    token: 1234567890:THISISATESTATOKENABCDEFGHUJIKLMNOPQ
