filename: app
spring:

  datasource:
    url: jdbc:mysql://localhost:3306/local
    username: local
    password: local

socnet:
  vk:
    appId: 123456789
    secretKey: "vk_secret_key"

alerter:
  telegram:
    chatId: -1234567890123
    token: 1234567890:THISISATESTATOKENABCDEFGHUJIKLMNOPQ
