filename: app
spring:

  application:
    name: gameplay-service

  datasource:
    url: ${DATASOURCE_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      trusted_packages: "m3.gameplay.dto.rq"
    topicName: 'topic-gameplay'

  profiles:
    group:
      home: local, suppress_useless_logs, home
      local: local, suppress_useless_logs

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

logging:
  level:
    root: info

alerter:
  telegram:
    chatId: ${TELEGRAM_CHAT_ID}
    token: ${TELEGRAM_TOKEN}

socnet:
  vk:
    appId: ${VK_APP_ID}
    secretKey: ${VK_SECRET_KEY}