filename: app
spring:

  datasource:
    url: jdbc:mysql://localhost:3306/local_database
    username: local_user
    password: local_password

socnet:
  vk:
    appId: 123456789
    secretKey: "vk_secret_key"
